# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  displayName: 'Compile the App'
  inputs:
    targetType: filePath
    filePath: 'Compile-PS.ps1'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: UniversalPackages@0
  displayName: mybcapp
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'BCPIP1/l4d'
    vstsFeedPackagePublish: 'mybcapp'
    packagePublishDescription: 'MyBCApp'

